# MQ connection information -------------------------------
qmgrConnectionParams:
# Queue manager name.
  qmgrName: QM
# Queue manager host.
  qmgrHost: hostname
# Queue manager connection port.
  qmgrPort: 1414
# Queue manager connection channel.
  qmgrChannel: SYSTEM.DEF.SVRCONN
# Username, which will be used for connection (optional).
# User must have permission to subscribe to the topic $SYS/MQ/INFO/QMGR/QM/Monitor/ and all subtopics.
# User also must have permission to inquire  channels, queues and listeners listed below in Monitoring objects section! 
  user: mqm
# Password, which will be used for connection (optional).
  password: mqm
# Use MQCSP for connection?
  mqscp: false

# Prometheus connection information -------------------------------
prometheusEndpointParams:
# URL and port which will be used to expose metrics for Prometheus.
  url: /metrics
  port: 8080


# Monitoring objects ----------------------------------
# This block refers to collecting of additional metrics.
# If there are any queues, channels or listeners in the config file below,
# these metrics may be useful for you. (More info about additional metrics is located 
# under "MQ PCF API specific statistics" section.   
PCFParameters:
# Collect additional metrics? If false, all settings in this section below are ignored. 
# If yes, additional metrics will be collected for all queues, channels and listeners listed below. 
  sendPCFCommands: true
# Use wildcards? If yes, only one PCF command will be send, matching all objects on queue manager. Otherwise, each 
# object will be monitored by separate PCF command.  
  usePCFWildcards: true
# Interval in seconds between sending PCF commands.
  scrapeInterval: 10

# Monitored queues.
queues:
  - QUEUE1
  - QUEUE2

# Monitored listeners.
listeners:
  - LISTENER01
 
# Monitored channels.
channels:
 - MANAGEMENT.CHANNEL